// This file was generated by
//     //sdk/android/native_api/jni_zero/jni_zero.py
// For
//     org.webrtc.audio.WebRtcAudioManager

#ifndef org_webrtc_audio_WebRtcAudioManager_JNI
#define org_webrtc_audio_WebRtcAudioManager_JNI

#include <jni.h>

#include "sdk/android/native_api/jni_zero/jni_export.h"

#include "sdk/android/src/jni/jni_generator_helper.h"
// Macro for transition to enable_definition_macros=true.
#define DEFINE_JNI_FOR_WebRtcAudioManager()

// Class Accessors
#ifndef org_webrtc_audio_WebRtcAudioManager_clazz_defined
#define org_webrtc_audio_WebRtcAudioManager_clazz_defined
inline jclass org_webrtc_audio_WebRtcAudioManager_clazz(JNIEnv* env) {
  static const char kClassName[] = "org/webrtc/audio/WebRtcAudioManager";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif

namespace webrtc::jni {

// Native to Java functions
static jni_zero::ScopedJavaLocalRef<jobject>
Java_WebRtcAudioManager_getAudioManager(
    JNIEnv* env, const jni_zero::JavaRef<jobject>& context) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioManager",
                                     "getAudioManager");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioManager_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env, clazz, "getAudioManager",
      "(Landroid/content/Context;)Landroid/media/AudioManager;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(),
                                          context.obj());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

static jint Java_WebRtcAudioManager_getInputBufferSize(
    JNIEnv* env, const jni_zero::JavaRef<jobject>& context,
    const jni_zero::JavaRef<jobject>& audioManager, JniIntWrapper sampleRate,
    JniIntWrapper numberOfInputChannels) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioManager",
                                     "getInputBufferSize");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioManager_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env, clazz, "getInputBufferSize",
      "(Landroid/content/Context;Landroid/media/AudioManager;II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(
      clazz, call_context.method_id(), context.obj(), audioManager.obj(),
      as_jint(sampleRate), as_jint(numberOfInputChannels));
  return _ret;
}

static jint Java_WebRtcAudioManager_getOutputBufferSize(
    JNIEnv* env, const jni_zero::JavaRef<jobject>& context,
    const jni_zero::JavaRef<jobject>& audioManager, JniIntWrapper sampleRate,
    JniIntWrapper numberOfOutputChannels) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioManager",
                                     "getOutputBufferSize");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioManager_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env, clazz, "getOutputBufferSize",
      "(Landroid/content/Context;Landroid/media/AudioManager;II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(
      clazz, call_context.method_id(), context.obj(), audioManager.obj(),
      as_jint(sampleRate), as_jint(numberOfOutputChannels));
  return _ret;
}

static jint Java_WebRtcAudioManager_getSampleRate(
    JNIEnv* env, const jni_zero::JavaRef<jobject>& audioManager) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioManager",
                                     "getSampleRate");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioManager_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env, clazz, "getSampleRate", "(Landroid/media/AudioManager;)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(),
                                       audioManager.obj());
  return _ret;
}

static jboolean Java_WebRtcAudioManager_isLowLatencyInputSupported(
    JNIEnv* env, const jni_zero::JavaRef<jobject>& context) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioManager",
                                     "isLowLatencyInputSupported");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioManager_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env, clazz, "isLowLatencyInputSupported", "(Landroid/content/Context;)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(),
                                           context.obj());
  return _ret;
}

static jboolean Java_WebRtcAudioManager_isLowLatencyOutputSupported(
    JNIEnv* env, const jni_zero::JavaRef<jobject>& context) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioManager",
                                     "isLowLatencyOutputSupported");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioManager_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env, clazz, "isLowLatencyOutputSupported", "(Landroid/content/Context;)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(),
                                           context.obj());
  return _ret;
}

}  // namespace webrtc::jni

#endif  // org_webrtc_audio_WebRtcAudioManager_JNI
