// This file was generated by
//     //sdk/android/native_api/jni_zero/jni_zero.py
// For
//     java.lang.Boolean

#ifndef java_lang_Boolean_JNI
#define java_lang_Boolean_JNI

#include <jni.h>

#include "sdk/android/native_api/jni_zero/jni_export.h"
#include "sdk/android/src/jni/jni_generator_helper.h"
// Macro for transition to enable_definition_macros=true.
#define DEFINE_JNI_FOR_Boolean()

// Class Accessors
#ifndef java_lang_Boolean_clazz_defined
#define java_lang_Boolean_clazz_defined
inline jclass java_lang_Boolean_clazz(JNIEnv* env) {
  static const char kClassName[] = "java/lang/Boolean";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace JNI_Boolean {

// Native to Java functions
[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Boolean_Constructor__boolean(
    JNIEnv* env,
    jboolean p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Boolean", "<init>");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Z)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), p0);
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Boolean_Constructor__String(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Boolean", "<init>");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Ljava/lang/String;)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), p0.obj());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jboolean Java_Boolean_booleanValue(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Boolean", "booleanValue");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "booleanValue",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jint Java_Boolean_compare(JNIEnv* env, jboolean p0, jboolean p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Boolean", "compare");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "compare",
      "(ZZ)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static jint Java_Boolean_compareTo__Boolean(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj,
    const jni_zero::JavaRef<jobject>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Boolean", "compareTo");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "compareTo",
      "(Ljava/lang/Boolean;)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static jint Java_Boolean_compareTo__Object(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj,
    const jni_zero::JavaRef<jobject>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Boolean", "compareTo");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "compareTo",
      "(Ljava/lang/Object;)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static jboolean Java_Boolean_equals(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj,
    const jni_zero::JavaRef<jobject>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Boolean", "equals");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "equals",
      "(Ljava/lang/Object;)Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static jboolean Java_Boolean_getBoolean(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Boolean", "getBoolean");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getBoolean",
      "(Ljava/lang/String;)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static jint Java_Boolean_hashCode(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Boolean", "hashCode");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "hashCode",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jint Java_Boolean_hashCode(JNIEnv* env, jboolean p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Boolean", "hashCode");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "hashCode",
      "(Z)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static jboolean Java_Boolean_logicalAnd(JNIEnv* env, jboolean p0, jboolean p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Boolean", "logicalAnd");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "logicalAnd",
      "(ZZ)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static jboolean Java_Boolean_logicalOr(JNIEnv* env, jboolean p0, jboolean p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Boolean", "logicalOr");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "logicalOr",
      "(ZZ)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static jboolean Java_Boolean_logicalXor(JNIEnv* env, jboolean p0, jboolean p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Boolean", "logicalXor");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "logicalXor",
      "(ZZ)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static jboolean Java_Boolean_parseBoolean(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Boolean", "parseBoolean");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseBoolean",
      "(Ljava/lang/String;)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jstring> Java_Boolean_toString(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Boolean", "toString");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "toString",
      "()Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jstring> Java_Boolean_toString(
    JNIEnv* env,
    jboolean p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Boolean", "toString");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toString",
      "(Z)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0);
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Boolean_valueOf__boolean(
    JNIEnv* env,
    jboolean p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Boolean", "valueOf");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "valueOf",
      "(Z)Ljava/lang/Boolean;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0);
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Boolean_valueOf__String(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Boolean", "valueOf");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Boolean_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "valueOf",
      "(Ljava/lang/String;)Ljava/lang/Boolean;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}



}  // namespace JNI_Boolean

#endif  // java_lang_Boolean_JNI
