// This file was generated by
//     //sdk/android/native_api/jni_zero/jni_zero.py
// For
//     java.lang.Double

#ifndef java_lang_Double_JNI
#define java_lang_Double_JNI

#include <jni.h>

#include "sdk/android/native_api/jni_zero/jni_export.h"
#include "sdk/android/src/jni/jni_generator_helper.h"
// Macro for transition to enable_definition_macros=true.
#define DEFINE_JNI_FOR_Double()

// Class Accessors
#ifndef java_lang_Double_clazz_defined
#define java_lang_Double_clazz_defined
inline jclass java_lang_Double_clazz(JNIEnv* env) {
  static const char kClassName[] = "java/lang/Double";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace JNI_Double {

// Constants
enum Java_Double_constant_fields {
  BYTES = 8,
  MAX_EXPONENT = 1023,
  PRECISION = 53,
  SIZE = 64,
};


// Native to Java functions
[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Double_Constructor__double(
    JNIEnv* env,
    jdouble p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "<init>");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(D)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), p0);
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Double_Constructor__String(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "<init>");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Ljava/lang/String;)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), p0.obj());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jbyte Java_Double_byteValue(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "byteValue");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "byteValue",
      "()B",
      &cached_method_id);
  auto _ret = env->CallByteMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jint Java_Double_compare(JNIEnv* env, jdouble p0, jdouble p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "compare");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "compare",
      "(DD)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static jint Java_Double_compareTo__Double(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj,
    const jni_zero::JavaRef<jobject>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "compareTo");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "compareTo",
      "(Ljava/lang/Double;)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static jint Java_Double_compareTo__Object(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj,
    const jni_zero::JavaRef<jobject>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "compareTo");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "compareTo",
      "(Ljava/lang/Object;)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static jlong Java_Double_doubleToLongBits(JNIEnv* env, jdouble p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "doubleToLongBits");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "doubleToLongBits",
      "(D)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static jlong Java_Double_doubleToRawLongBits(JNIEnv* env, jdouble p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "doubleToRawLongBits");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "doubleToRawLongBits",
      "(D)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static jdouble Java_Double_doubleValue(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "doubleValue");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "doubleValue",
      "()D",
      &cached_method_id);
  auto _ret = env->CallDoubleMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jboolean Java_Double_equals(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj,
    const jni_zero::JavaRef<jobject>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "equals");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "equals",
      "(Ljava/lang/Object;)Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static jfloat Java_Double_floatValue(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "floatValue");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "floatValue",
      "()F",
      &cached_method_id);
  auto _ret = env->CallFloatMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jint Java_Double_hashCode(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "hashCode");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "hashCode",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jint Java_Double_hashCode(JNIEnv* env, jdouble p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "hashCode");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "hashCode",
      "(D)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static jint Java_Double_intValue(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "intValue");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "intValue",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jboolean Java_Double_isFinite(JNIEnv* env, jdouble p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "isFinite");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "isFinite",
      "(D)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static jboolean Java_Double_isInfinite(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "isInfinite");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "isInfinite",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jboolean Java_Double_isInfinite(JNIEnv* env, jdouble p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "isInfinite");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "isInfinite",
      "(D)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static jboolean Java_Double_isNaN(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "isNaN");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "isNaN",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jboolean Java_Double_isNaN(JNIEnv* env, jdouble p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "isNaN");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "isNaN",
      "(D)Z",
      &cached_method_id);
  auto _ret = env->CallStaticBooleanMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static jdouble Java_Double_longBitsToDouble(JNIEnv* env, jlong p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "longBitsToDouble");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "longBitsToDouble",
      "(J)D",
      &cached_method_id);
  auto _ret = env->CallStaticDoubleMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static jlong Java_Double_longValue(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "longValue");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "longValue",
      "()J",
      &cached_method_id);
  auto _ret = env->CallLongMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jdouble Java_Double_max(JNIEnv* env, jdouble p0, jdouble p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "max");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "max",
      "(DD)D",
      &cached_method_id);
  auto _ret = env->CallStaticDoubleMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static jdouble Java_Double_min(JNIEnv* env, jdouble p0, jdouble p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "min");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "min",
      "(DD)D",
      &cached_method_id);
  auto _ret = env->CallStaticDoubleMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static jdouble Java_Double_parseDouble(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "parseDouble");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseDouble",
      "(Ljava/lang/String;)D",
      &cached_method_id);
  auto _ret = env->CallStaticDoubleMethod(clazz, call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static jshort Java_Double_shortValue(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "shortValue");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "shortValue",
      "()S",
      &cached_method_id);
  auto _ret = env->CallShortMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jdouble Java_Double_sum(JNIEnv* env, jdouble p0, jdouble p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "sum");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "sum",
      "(DD)D",
      &cached_method_id);
  auto _ret = env->CallStaticDoubleMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jstring> Java_Double_toHexString(
    JNIEnv* env,
    jdouble p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "toHexString");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toHexString",
      "(D)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0);
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jstring> Java_Double_toString(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "toString");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "toString",
      "()Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jstring> Java_Double_toString(
    JNIEnv* env,
    jdouble p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "toString");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toString",
      "(D)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0);
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Double_valueOf__double(
    JNIEnv* env,
    jdouble p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "valueOf");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "valueOf",
      "(D)Ljava/lang/Double;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0);
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Double_valueOf__String(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Double", "valueOf");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Double_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "valueOf",
      "(Ljava/lang/String;)Ljava/lang/Double;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}



}  // namespace JNI_Double

#endif  // java_lang_Double_JNI
