// This file was generated by
//     //sdk/android/native_api/jni_zero/jni_zero.py
// For
//     java.lang.Enum

#ifndef java_lang_Enum_JNI
#define java_lang_Enum_JNI

#include <jni.h>

#include "sdk/android/native_api/jni_zero/jni_export.h"
#include "sdk/android/src/jni/jni_generator_helper.h"
// Macro for transition to enable_definition_macros=true.
#define DEFINE_JNI_FOR_Enum()

// Class Accessors
#ifndef java_lang_Enum_clazz_defined
#define java_lang_Enum_clazz_defined
inline jclass java_lang_Enum_clazz(JNIEnv* env) {
  static const char kClassName[] = "java/lang/Enum";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace JNI_Enum {

// Native to Java functions
[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Enum_Constructor(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0,
    JniIntWrapper p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Enum", "<init>");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Enum_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Ljava/lang/String;I)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), p0.obj(), as_jint(p1));
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Enum_clone(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Enum", "clone");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Enum_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "clone",
      "()Ljava/lang/Object;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jint Java_Enum_compareTo__Enum(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj,
    const jni_zero::JavaRef<jobject>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Enum", "compareTo");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Enum_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "compareTo",
      "(Ljava/lang/Enum;)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static jint Java_Enum_compareTo__Object(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj,
    const jni_zero::JavaRef<jobject>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Enum", "compareTo");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Enum_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "compareTo",
      "(Ljava/lang/Object;)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static jboolean Java_Enum_equals(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj,
    const jni_zero::JavaRef<jobject>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Enum", "equals");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Enum_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "equals",
      "(Ljava/lang/Object;)Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static void Java_Enum_finalize(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Enum", "finalize");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Enum_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "finalize",
      "()V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id());
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jclass> Java_Enum_getDeclaringClass(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Enum", "getDeclaringClass");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Enum_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getDeclaringClass",
      "()Ljava/lang/Class;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jclass _ret2 = static_cast<jclass>(_ret);
  return jni_zero::ScopedJavaLocalRef<jclass>(env, _ret2);
}

[[maybe_unused]] static jint Java_Enum_hashCode(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Enum", "hashCode");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Enum_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "hashCode",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jstring> Java_Enum_name(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Enum", "name");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Enum_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "name",
      "()Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

[[maybe_unused]] static jint Java_Enum_ordinal(JNIEnv* env, const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Enum", "ordinal");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Enum_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "ordinal",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jstring> Java_Enum_toString(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Enum", "toString");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Enum_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "toString",
      "()Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Enum_valueOf(
    JNIEnv* env,
    const jni_zero::JavaRef<jclass>& p0,
    const jni_zero::JavaRef<jstring>& p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Enum", "valueOf");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Enum_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "valueOf",
      "(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/Enum;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj(), p1.obj());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}



}  // namespace JNI_Enum

#endif  // java_lang_Enum_JNI
