// This file was generated by
//     //sdk/android/native_api/jni_zero/jni_zero.py
// For
//     java.lang.Integer

#ifndef java_lang_Integer_JNI
#define java_lang_Integer_JNI

#include <jni.h>

#include "sdk/android/native_api/jni_zero/jni_export.h"
#include "sdk/android/src/jni/jni_generator_helper.h"
// Macro for transition to enable_definition_macros=true.
#define DEFINE_JNI_FOR_Integer()

// Class Accessors
#ifndef java_lang_Integer_clazz_defined
#define java_lang_Integer_clazz_defined
inline jclass java_lang_Integer_clazz(JNIEnv* env) {
  static const char kClassName[] = "java/lang/Integer";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace JNI_Integer {

// Constants
enum Java_Integer_constant_fields {
  BYTES = 4,
  MAX_VALUE = 2147483647,
  SIZE = 32,
};


// Native to Java functions
[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Integer_Constructor__int(
    JNIEnv* env,
    JniIntWrapper p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "<init>");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(I)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), as_jint(p0));
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Integer_Constructor__String(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "<init>");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Ljava/lang/String;)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), p0.obj());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jint Java_Integer_bitCount(JNIEnv* env, JniIntWrapper p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "bitCount");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "bitCount",
      "(I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static jbyte Java_Integer_byteValue(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "byteValue");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "byteValue",
      "()B",
      &cached_method_id);
  auto _ret = env->CallByteMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_compare(JNIEnv* env, JniIntWrapper p0, JniIntWrapper p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "compare");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "compare",
      "(II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_compareTo__Integer(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj,
    const jni_zero::JavaRef<jobject>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "compareTo");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "compareTo",
      "(Ljava/lang/Integer;)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_compareTo__Object(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj,
    const jni_zero::JavaRef<jobject>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "compareTo");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "compareTo",
      "(Ljava/lang/Object;)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_compareUnsigned(
    JNIEnv* env,
    JniIntWrapper p0,
    JniIntWrapper p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "compareUnsigned");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "compareUnsigned",
      "(II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Integer_decode(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "decode");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "decode",
      "(Ljava/lang/String;)Ljava/lang/Integer;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jint Java_Integer_divideUnsigned(
    JNIEnv* env,
    JniIntWrapper p0,
    JniIntWrapper p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "divideUnsigned");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "divideUnsigned",
      "(II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static jdouble Java_Integer_doubleValue(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "doubleValue");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "doubleValue",
      "()D",
      &cached_method_id);
  auto _ret = env->CallDoubleMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jboolean Java_Integer_equals(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj,
    const jni_zero::JavaRef<jobject>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "equals");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "equals",
      "(Ljava/lang/Object;)Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static jfloat Java_Integer_floatValue(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "floatValue");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "floatValue",
      "()F",
      &cached_method_id);
  auto _ret = env->CallFloatMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Integer_getInteger(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "getInteger");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getInteger",
      "(Ljava/lang/String;)Ljava/lang/Integer;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Integer_getInteger__String__int(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0,
    JniIntWrapper p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "getInteger");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getInteger",
      "(Ljava/lang/String;I)Ljava/lang/Integer;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj(), as_jint(p1));
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Integer_getInteger__String__Integer(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0,
    const jni_zero::JavaRef<jobject>& p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "getInteger");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getInteger",
      "(Ljava/lang/String;Ljava/lang/Integer;)Ljava/lang/Integer;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj(), p1.obj());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jint Java_Integer_hashCode(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "hashCode");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "hashCode",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_hashCode(JNIEnv* env, JniIntWrapper p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "hashCode");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "hashCode",
      "(I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_highestOneBit(JNIEnv* env, JniIntWrapper p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "highestOneBit");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "highestOneBit",
      "(I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_intValue(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "intValue");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "intValue",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jlong Java_Integer_longValue(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "longValue");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "longValue",
      "()J",
      &cached_method_id);
  auto _ret = env->CallLongMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_lowestOneBit(JNIEnv* env, JniIntWrapper p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "lowestOneBit");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "lowestOneBit",
      "(I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_max(JNIEnv* env, JniIntWrapper p0, JniIntWrapper p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "max");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "max",
      "(II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_min(JNIEnv* env, JniIntWrapper p0, JniIntWrapper p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "min");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "min",
      "(II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_numberOfLeadingZeros(JNIEnv* env, JniIntWrapper p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "numberOfLeadingZeros");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "numberOfLeadingZeros",
      "(I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_numberOfTrailingZeros(JNIEnv* env, JniIntWrapper p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "numberOfTrailingZeros");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "numberOfTrailingZeros",
      "(I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_parseInt(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& p0,
    JniIntWrapper p1,
    JniIntWrapper p2,
    JniIntWrapper p3) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "parseInt");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseInt",
      "(Ljava/lang/CharSequence;III)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(
      clazz,
      call_context.method_id(),
      p0.obj(),
      as_jint(p1),
      as_jint(p2),
      as_jint(p3));
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_parseInt(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "parseInt");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseInt",
      "(Ljava/lang/String;)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_parseInt(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0,
    JniIntWrapper p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "parseInt");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseInt",
      "(Ljava/lang/String;I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0.obj(), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_parseUnsignedInt(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& p0,
    JniIntWrapper p1,
    JniIntWrapper p2,
    JniIntWrapper p3) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "parseUnsignedInt");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseUnsignedInt",
      "(Ljava/lang/CharSequence;III)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(
      clazz,
      call_context.method_id(),
      p0.obj(),
      as_jint(p1),
      as_jint(p2),
      as_jint(p3));
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_parseUnsignedInt(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "parseUnsignedInt");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseUnsignedInt",
      "(Ljava/lang/String;)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_parseUnsignedInt(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0,
    JniIntWrapper p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "parseUnsignedInt");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseUnsignedInt",
      "(Ljava/lang/String;I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0.obj(), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_remainderUnsigned(
    JNIEnv* env,
    JniIntWrapper p0,
    JniIntWrapper p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "remainderUnsigned");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "remainderUnsigned",
      "(II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_reverse(JNIEnv* env, JniIntWrapper p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "reverse");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "reverse",
      "(I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_reverseBytes(JNIEnv* env, JniIntWrapper p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "reverseBytes");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "reverseBytes",
      "(I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_rotateLeft(
    JNIEnv* env,
    JniIntWrapper p0,
    JniIntWrapper p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "rotateLeft");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "rotateLeft",
      "(II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_rotateRight(
    JNIEnv* env,
    JniIntWrapper p0,
    JniIntWrapper p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "rotateRight");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "rotateRight",
      "(II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static jshort Java_Integer_shortValue(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "shortValue");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "shortValue",
      "()S",
      &cached_method_id);
  auto _ret = env->CallShortMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_signum(JNIEnv* env, JniIntWrapper p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "signum");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "signum",
      "(I)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static jint Java_Integer_sum(JNIEnv* env, JniIntWrapper p0, JniIntWrapper p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "sum");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "sum",
      "(II)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), as_jint(p0), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jstring> Java_Integer_toBinaryString(
    JNIEnv* env,
    JniIntWrapper p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "toBinaryString");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toBinaryString",
      "(I)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), as_jint(p0));
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jstring> Java_Integer_toHexString(
    JNIEnv* env,
    JniIntWrapper p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "toHexString");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toHexString",
      "(I)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), as_jint(p0));
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jstring> Java_Integer_toOctalString(
    JNIEnv* env,
    JniIntWrapper p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "toOctalString");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toOctalString",
      "(I)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), as_jint(p0));
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jstring> Java_Integer_toString(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "toString");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "toString",
      "()Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jstring> Java_Integer_toString(
    JNIEnv* env,
    JniIntWrapper p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "toString");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toString",
      "(I)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), as_jint(p0));
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jstring> Java_Integer_toString(
    JNIEnv* env,
    JniIntWrapper p0,
    JniIntWrapper p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "toString");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toString",
      "(II)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(
      clazz,
      call_context.method_id(),
      as_jint(p0),
      as_jint(p1));
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

[[maybe_unused]] static jlong Java_Integer_toUnsignedLong(JNIEnv* env, JniIntWrapper p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "toUnsignedLong");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toUnsignedLong",
      "(I)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), as_jint(p0));
  return _ret;
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jstring> Java_Integer_toUnsignedString(
    JNIEnv* env,
    JniIntWrapper p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "toUnsignedString");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toUnsignedString",
      "(I)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), as_jint(p0));
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jstring> Java_Integer_toUnsignedString(
    JNIEnv* env,
    JniIntWrapper p0,
    JniIntWrapper p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "toUnsignedString");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toUnsignedString",
      "(II)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(
      clazz,
      call_context.method_id(),
      as_jint(p0),
      as_jint(p1));
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Integer_valueOf__int(
    JNIEnv* env,
    JniIntWrapper p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "valueOf");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "valueOf",
      "(I)Ljava/lang/Integer;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), as_jint(p0));
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Integer_valueOf__String(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "valueOf");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "valueOf",
      "(Ljava/lang/String;)Ljava/lang/Integer;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Integer_valueOf(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0,
    JniIntWrapper p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Integer", "valueOf");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Integer_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "valueOf",
      "(Ljava/lang/String;I)Ljava/lang/Integer;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj(), as_jint(p1));
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}



}  // namespace JNI_Integer

#endif  // java_lang_Integer_JNI
