// This file was generated by
//     //sdk/android/native_api/jni_zero/jni_zero.py
// For
//     java.lang.Iterable

#ifndef java_lang_Iterable_JNI
#define java_lang_Iterable_JNI

#include <jni.h>

#include "sdk/android/native_api/jni_zero/jni_export.h"
#include "sdk/android/src/jni/jni_generator_helper.h"
// Macro for transition to enable_definition_macros=true.
#define DEFINE_JNI_FOR_Iterable()

// Class Accessors
#ifndef java_lang_Iterable_clazz_defined
#define java_lang_Iterable_clazz_defined
inline jclass java_lang_Iterable_clazz(JNIEnv* env) {
  static const char kClassName[] = "java/lang/Iterable";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace JNI_Iterable {

// Native to Java functions
[[maybe_unused]] static void Java_Iterable_forEach(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj,
    const jni_zero::JavaRef<jobject>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Iterable", "forEach");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Iterable_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "forEach",
      "(Ljava/util/function/Consumer;)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), p0.obj());
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Iterable_iterator(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Iterable", "iterator");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Iterable_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "iterator",
      "()Ljava/util/Iterator;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Iterable_spliterator(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Iterable", "spliterator");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Iterable_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "spliterator",
      "()Ljava/util/Spliterator;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}



}  // namespace JNI_Iterable

#endif  // java_lang_Iterable_JNI
