// This file was generated by
//     //sdk/android/native_api/jni_zero/jni_zero.py
// For
//     java.lang.Long

#ifndef java_lang_Long_JNI
#define java_lang_Long_JNI

#include <jni.h>

#include "sdk/android/native_api/jni_zero/jni_export.h"
#include "sdk/android/src/jni/jni_generator_helper.h"
// Macro for transition to enable_definition_macros=true.
#define DEFINE_JNI_FOR_Long()

// Class Accessors
#ifndef java_lang_Long_clazz_defined
#define java_lang_Long_clazz_defined
inline jclass java_lang_Long_clazz(JNIEnv* env) {
  static const char kClassName[] = "java/lang/Long";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace JNI_Long {

// Constants
enum Java_Long_constant_fields {
  BYTES = 8,
  SIZE = 64,
};


// Native to Java functions
[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Long_Constructor__long(
    JNIEnv* env,
    jlong p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "<init>");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(J)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), p0);
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Long_Constructor__String(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "<init>");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Ljava/lang/String;)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), p0.obj());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jint Java_Long_bitCount(JNIEnv* env, jlong p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "bitCount");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "bitCount",
      "(J)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static jbyte Java_Long_byteValue(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "byteValue");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "byteValue",
      "()B",
      &cached_method_id);
  auto _ret = env->CallByteMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jint Java_Long_compare(JNIEnv* env, jlong p0, jlong p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "compare");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "compare",
      "(JJ)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static jint Java_Long_compareTo__Long(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj,
    const jni_zero::JavaRef<jobject>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "compareTo");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "compareTo",
      "(Ljava/lang/Long;)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static jint Java_Long_compareTo__Object(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj,
    const jni_zero::JavaRef<jobject>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "compareTo");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "compareTo",
      "(Ljava/lang/Object;)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static jint Java_Long_compareUnsigned(JNIEnv* env, jlong p0, jlong p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "compareUnsigned");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "compareUnsigned",
      "(JJ)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Long_decode(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "decode");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "decode",
      "(Ljava/lang/String;)Ljava/lang/Long;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jlong Java_Long_divideUnsigned(JNIEnv* env, jlong p0, jlong p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "divideUnsigned");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "divideUnsigned",
      "(JJ)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static jdouble Java_Long_doubleValue(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "doubleValue");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "doubleValue",
      "()D",
      &cached_method_id);
  auto _ret = env->CallDoubleMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jboolean Java_Long_equals(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj,
    const jni_zero::JavaRef<jobject>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "equals");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "equals",
      "(Ljava/lang/Object;)Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static jfloat Java_Long_floatValue(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "floatValue");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "floatValue",
      "()F",
      &cached_method_id);
  auto _ret = env->CallFloatMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Long_getLong(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "getLong");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getLong",
      "(Ljava/lang/String;)Ljava/lang/Long;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Long_getLong__String__long(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0,
    jlong p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "getLong");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getLong",
      "(Ljava/lang/String;J)Ljava/lang/Long;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj(), p1);
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Long_getLong__String__Long(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0,
    const jni_zero::JavaRef<jobject>& p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "getLong");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "getLong",
      "(Ljava/lang/String;Ljava/lang/Long;)Ljava/lang/Long;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj(), p1.obj());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jint Java_Long_hashCode(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "hashCode");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "hashCode",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jint Java_Long_hashCode(JNIEnv* env, jlong p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "hashCode");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "hashCode",
      "(J)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static jlong Java_Long_highestOneBit(JNIEnv* env, jlong p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "highestOneBit");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "highestOneBit",
      "(J)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static jint Java_Long_intValue(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "intValue");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "intValue",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jlong Java_Long_longValue(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "longValue");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "longValue",
      "()J",
      &cached_method_id);
  auto _ret = env->CallLongMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jlong Java_Long_lowestOneBit(JNIEnv* env, jlong p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "lowestOneBit");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "lowestOneBit",
      "(J)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static jlong Java_Long_max(JNIEnv* env, jlong p0, jlong p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "max");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "max",
      "(JJ)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static jlong Java_Long_min(JNIEnv* env, jlong p0, jlong p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "min");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "min",
      "(JJ)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static jint Java_Long_numberOfLeadingZeros(JNIEnv* env, jlong p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "numberOfLeadingZeros");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "numberOfLeadingZeros",
      "(J)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static jint Java_Long_numberOfTrailingZeros(JNIEnv* env, jlong p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "numberOfTrailingZeros");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "numberOfTrailingZeros",
      "(J)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static jlong Java_Long_parseLong(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& p0,
    JniIntWrapper p1,
    JniIntWrapper p2,
    JniIntWrapper p3) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "parseLong");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseLong",
      "(Ljava/lang/CharSequence;III)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(
      clazz,
      call_context.method_id(),
      p0.obj(),
      as_jint(p1),
      as_jint(p2),
      as_jint(p3));
  return _ret;
}

[[maybe_unused]] static jlong Java_Long_parseLong(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "parseLong");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseLong",
      "(Ljava/lang/String;)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static jlong Java_Long_parseLong(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0,
    JniIntWrapper p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "parseLong");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseLong",
      "(Ljava/lang/String;I)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0.obj(), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static jlong Java_Long_parseUnsignedLong(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& p0,
    JniIntWrapper p1,
    JniIntWrapper p2,
    JniIntWrapper p3) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "parseUnsignedLong");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseUnsignedLong",
      "(Ljava/lang/CharSequence;III)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(
      clazz,
      call_context.method_id(),
      p0.obj(),
      as_jint(p1),
      as_jint(p2),
      as_jint(p3));
  return _ret;
}

[[maybe_unused]] static jlong Java_Long_parseUnsignedLong(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "parseUnsignedLong");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseUnsignedLong",
      "(Ljava/lang/String;)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0.obj());
  return _ret;
}

[[maybe_unused]] static jlong Java_Long_parseUnsignedLong(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0,
    JniIntWrapper p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "parseUnsignedLong");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "parseUnsignedLong",
      "(Ljava/lang/String;I)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0.obj(), as_jint(p1));
  return _ret;
}

[[maybe_unused]] static jlong Java_Long_remainderUnsigned(JNIEnv* env, jlong p0, jlong p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "remainderUnsigned");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "remainderUnsigned",
      "(JJ)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static jlong Java_Long_reverse(JNIEnv* env, jlong p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "reverse");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "reverse",
      "(J)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static jlong Java_Long_reverseBytes(JNIEnv* env, jlong p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "reverseBytes");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "reverseBytes",
      "(J)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static jlong Java_Long_rotateLeft(JNIEnv* env, jlong p0, JniIntWrapper p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "rotateLeft");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "rotateLeft",
      "(JI)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0, as_jint(p1));
  return _ret;
}

[[maybe_unused]] static jlong Java_Long_rotateRight(JNIEnv* env, jlong p0, JniIntWrapper p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "rotateRight");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "rotateRight",
      "(JI)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0, as_jint(p1));
  return _ret;
}

[[maybe_unused]] static jshort Java_Long_shortValue(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "shortValue");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "shortValue",
      "()S",
      &cached_method_id);
  auto _ret = env->CallShortMethod(obj.obj(), call_context.method_id());
  return _ret;
}

[[maybe_unused]] static jint Java_Long_signum(JNIEnv* env, jlong p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "signum");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "signum",
      "(J)I",
      &cached_method_id);
  auto _ret = env->CallStaticIntMethod(clazz, call_context.method_id(), p0);
  return _ret;
}

[[maybe_unused]] static jlong Java_Long_sum(JNIEnv* env, jlong p0, jlong p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "sum");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "sum",
      "(JJ)J",
      &cached_method_id);
  auto _ret = env->CallStaticLongMethod(clazz, call_context.method_id(), p0, p1);
  return _ret;
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jstring> Java_Long_toBinaryString(
    JNIEnv* env,
    jlong p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "toBinaryString");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toBinaryString",
      "(J)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0);
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jstring> Java_Long_toHexString(
    JNIEnv* env,
    jlong p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "toHexString");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toHexString",
      "(J)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0);
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jstring> Java_Long_toOctalString(
    JNIEnv* env,
    jlong p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "toOctalString");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toOctalString",
      "(J)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0);
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jstring> Java_Long_toString(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "toString");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "toString",
      "()Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallObjectMethod(obj.obj(), call_context.method_id());
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jstring> Java_Long_toString(
    JNIEnv* env,
    jlong p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "toString");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toString",
      "(J)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0);
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jstring> Java_Long_toString(
    JNIEnv* env,
    jlong p0,
    JniIntWrapper p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "toString");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toString",
      "(JI)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0, as_jint(p1));
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jstring> Java_Long_toUnsignedString(
    JNIEnv* env,
    jlong p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "toUnsignedString");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toUnsignedString",
      "(J)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0);
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jstring> Java_Long_toUnsignedString(
    JNIEnv* env,
    jlong p0,
    JniIntWrapper p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "toUnsignedString");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "toUnsignedString",
      "(JI)Ljava/lang/String;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0, as_jint(p1));
  jstring _ret2 = static_cast<jstring>(_ret);
  return jni_zero::ScopedJavaLocalRef<jstring>(env, _ret2);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Long_valueOf__long(
    JNIEnv* env,
    jlong p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "valueOf");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "valueOf",
      "(J)Ljava/lang/Long;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0);
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Long_valueOf__String(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "valueOf");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "valueOf",
      "(Ljava/lang/String;)Ljava/lang/Long;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

[[maybe_unused]] static jni_zero::ScopedJavaLocalRef<jobject> Java_Long_valueOf(
    JNIEnv* env,
    const jni_zero::JavaRef<jstring>& p0,
    JniIntWrapper p1) {
  jni_zero::CallNativeToJavaCallback("java/lang/Long", "valueOf");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = java_lang_Long_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env,
      clazz,
      "valueOf",
      "(Ljava/lang/String;I)Ljava/lang/Long;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id(), p0.obj(), as_jint(p1));
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}



}  // namespace JNI_Long

#endif  // java_lang_Long_JNI
