# Copyright (c) 2018 The WebRTC project authors. All Rights Reserved.
#
# Use of this source code is governed by a BSD-style license
# that can be found in the LICENSE file in the root of the source
# tree. An additional intellectual property rights grant can be found
# in the file PATENTS.  All contributing project authors may
# be found in the AUTHORS file in the root of the source tree.

import("../../webrtc.gni")

rtc_source_set("audio_device") {
  visibility = [ "*" ]
  sources = [
    "audio_device.h",
    "audio_device_defines.h",
  ]
  deps = [
    "..:ref_count",
    "..:scoped_refptr",
    "../../rtc_base:checks",
    "../../rtc_base:stringutils",
    "../task_queue",
  ]
}

rtc_library("audio_frame_api") {
  visibility = [ "*" ]
  sources = [
    "audio_frame.cc",
    "audio_frame.h",
    "audio_view.h",
    "channel_layout.cc",
    "channel_layout.h",
  ]

  deps = [
    "..:array_view",
    "../../rtc_base:checks",
    "../../rtc_base:logging",
    "../../rtc_base:macromagic",
    "../../rtc_base:timeutils",
  ]
}

rtc_source_set("audio_mixer_api") {
  visibility = [ "*" ]
  sources = [ "audio_mixer.h" ]

  deps = [
    ":audio_frame_api",
    "..:make_ref_counted",
    "../../rtc_base:refcount",
  ]
}

