// This file was generated by
//     //sdk/android/native_api/jni_zero/jni_zero.py
// For
//     org.webrtc.ApplicationContextProvider

#ifndef org_webrtc_ApplicationContextProvider_JNI
#define org_webrtc_ApplicationContextProvider_JNI

#include <jni.h>

#include "sdk/android/native_api/jni_zero/jni_export.h"

#include "sdk/android/src/jni/jni_generator_helper.h"
// Macro for transition to enable_definition_macros=true.
#define DEFINE_JNI_FOR_ApplicationContextProvider()

// Class Accessors
#ifndef org_webrtc_ApplicationContextProvider_clazz_defined
#define org_webrtc_ApplicationContextProvider_clazz_defined
inline jclass org_webrtc_ApplicationContextProvider_clazz(JNIEnv* env) {
  static const char kClassName[] = "org/webrtc/ApplicationContextProvider";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif

namespace webrtc::jni {

// Native to Java functions
static jni_zero::ScopedJavaLocalRef<jobject>
Java_ApplicationContextProvider_getApplicationContext(JNIEnv* env) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/ApplicationContextProvider",
                                     "getApplicationContext");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_ApplicationContextProvider_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env, clazz, "getApplicationContext", "()Landroid/content/Context;",
      &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

}  // namespace webrtc::jni

#endif  // org_webrtc_ApplicationContextProvider_JNI
