// This file was generated by
//     //sdk/android/native_api/jni_zero/jni_zero.py
// For
//     org.webrtc.JniHelper

#ifndef org_webrtc_JniHelper_JNI
#define org_webrtc_JniHelper_JNI

#include <jni.h>

#include "sdk/android/native_api/jni_zero/jni_export.h"

#include "sdk/android/src/jni/jni_generator_helper.h"
// Macro for transition to enable_definition_macros=true.
#define DEFINE_JNI_FOR_JniHelper()

// Class Accessors
#ifndef org_webrtc_JniHelper_clazz_defined
#define org_webrtc_JniHelper_clazz_defined
inline jclass org_webrtc_JniHelper_clazz(JNIEnv* env) {
  static const char kClassName[] = "org/webrtc/JniHelper";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif

namespace webrtc::jni {

// Native to Java functions
static jni_zero::ScopedJavaLocalRef<jobject> Java_JniHelper_getKey(
    JNIEnv* env, const jni_zero::JavaRef<jobject>& entry) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/JniHelper", "getKey");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_JniHelper_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env, clazz, "getKey", "(Ljava/util/Map$Entry;)Ljava/lang/Object;",
      &cached_method_id);
  auto _ret =
      env->CallStaticObjectMethod(clazz, call_context.method_id(), entry.obj());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

static jni_zero::ScopedJavaLocalRef<jbyteArray> Java_JniHelper_getStringBytes(
    JNIEnv* env, const jni_zero::JavaRef<jstring>& s) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/JniHelper", "getStringBytes");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_JniHelper_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env, clazz, "getStringBytes", "(Ljava/lang/String;)[B",
      &cached_method_id);
  auto _ret =
      env->CallStaticObjectMethod(clazz, call_context.method_id(), s.obj());
  jbyteArray _ret2 = static_cast<jbyteArray>(_ret);
  return jni_zero::ScopedJavaLocalRef<jbyteArray>(env, _ret2);
}

static jni_zero::ScopedJavaLocalRef<jobject> Java_JniHelper_getStringClass(
    JNIEnv* env) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/JniHelper", "getStringClass");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_JniHelper_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env, clazz, "getStringClass", "()Ljava/lang/Object;", &cached_method_id);
  auto _ret = env->CallStaticObjectMethod(clazz, call_context.method_id());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

static jni_zero::ScopedJavaLocalRef<jobject> Java_JniHelper_getValue(
    JNIEnv* env, const jni_zero::JavaRef<jobject>& entry) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/JniHelper", "getValue");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_JniHelper_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_STATIC>(
      env, clazz, "getValue", "(Ljava/util/Map$Entry;)Ljava/lang/Object;",
      &cached_method_id);
  auto _ret =
      env->CallStaticObjectMethod(clazz, call_context.method_id(), entry.obj());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

}  // namespace webrtc::jni

#endif  // org_webrtc_JniHelper_JNI
