// This file was generated by
//     //sdk/android/native_api/jni_zero/jni_zero.py
// For
//     org.webrtc.audio.WebRtcAudioTrack

#ifndef org_webrtc_audio_WebRtcAudioTrack_JNI
#define org_webrtc_audio_WebRtcAudioTrack_JNI

#include <jni.h>

#include "sdk/android/native_api/jni_zero/jni_export.h"
#include "sdk/android/src/jni/jni_generator_helper.h"
// Macro for transition to enable_definition_macros=true.
#define DEFINE_JNI_FOR_WebRtcAudioTrack()

// Class Accessors
#ifndef org_webrtc_audio_WebRtcAudioTrack_clazz_defined
#define org_webrtc_audio_WebRtcAudioTrack_clazz_defined
inline jclass org_webrtc_audio_WebRtcAudioTrack_clazz(JNIEnv* env) {
  static const char kClassName[] = "org/webrtc/audio/WebRtcAudioTrack";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace webrtc::jni {

// Java to native functions
JNI_ZERO_BOUNDARY_EXPORT void Java_org_webrtc_audio_WebRtcAudioTrack_nativeCacheDirectBufferAddress(
    JNIEnv* env,
    jclass jcaller,
    jlong nativeAudioTrackJni,
    jobject byteBuffer) {
  reinterpret_cast<AudioTrackJni*>(nativeAudioTrackJni)->CacheDirectBufferAddress(
      env,
      jni_zero::JavaParamRef<jobject>(env, byteBuffer));
}

JNI_ZERO_BOUNDARY_EXPORT void Java_org_webrtc_audio_WebRtcAudioTrack_nativeGetPlayoutData(
    JNIEnv* env,
    jclass jcaller,
    jlong nativeAudioTrackJni,
    jint bytes) {
  reinterpret_cast<AudioTrackJni*>(nativeAudioTrackJni)->GetPlayoutData(env, bytes);
}


// Native to Java functions
static jni_zero::ScopedJavaLocalRef<jobject> Java_WebRtcAudioTrack_Constructor(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& context,
    const jni_zero::JavaRef<jobject>& audioManager) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioTrack", "<init>");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioTrack_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Landroid/content/Context;Landroid/media/AudioManager;)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), context.obj(), audioManager.obj());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

static jint Java_WebRtcAudioTrack_GetPlayoutUnderrunCount(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioTrack", "GetPlayoutUnderrunCount");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioTrack_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "GetPlayoutUnderrunCount",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static jint Java_WebRtcAudioTrack_getBufferSizeInFrames(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioTrack", "getBufferSizeInFrames");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioTrack_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getBufferSizeInFrames",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static jint Java_WebRtcAudioTrack_getInitialBufferSizeInFrames(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioTrack", "getInitialBufferSizeInFrames");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioTrack_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getInitialBufferSizeInFrames",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static jint Java_WebRtcAudioTrack_getStreamMaxVolume(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioTrack", "getStreamMaxVolume");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioTrack_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getStreamMaxVolume",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static jint Java_WebRtcAudioTrack_getStreamVolume(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioTrack", "getStreamVolume");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioTrack_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "getStreamVolume",
      "()I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static jint Java_WebRtcAudioTrack_initPlayout(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper sampleRate,
    JniIntWrapper channels,
    jdouble bufferSizeFactor) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioTrack", "initPlayout");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioTrack_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "initPlayout",
      "(IID)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(
      obj.obj(),
      call_context.method_id(),
      as_jint(sampleRate),
      as_jint(channels),
      bufferSizeFactor);
  return _ret;
}

static void Java_WebRtcAudioTrack_setNativeAudioTrack(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj,
    jlong nativeAudioTrack) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioTrack", "setNativeAudioTrack");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioTrack_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "setNativeAudioTrack",
      "(J)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), nativeAudioTrack);
}

static jboolean Java_WebRtcAudioTrack_setStreamVolume(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper volume) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioTrack", "setStreamVolume");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioTrack_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "setStreamVolume",
      "(I)Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id(), as_jint(volume));
  return _ret;
}

static jboolean Java_WebRtcAudioTrack_startPlayout(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioTrack", "startPlayout");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioTrack_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "startPlayout",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static jboolean Java_WebRtcAudioTrack_stopPlayout(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioTrack", "stopPlayout");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioTrack_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "stopPlayout",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}



}  // namespace webrtc::jni

#endif  // org_webrtc_audio_WebRtcAudioTrack_JNI
