// This file was generated by
//     //sdk/android/native_api/jni_zero/jni_zero.py
// For
//     org.webrtc.audio.WebRtcAudioRecord

#ifndef org_webrtc_audio_WebRtcAudioRecord_JNI
#define org_webrtc_audio_WebRtcAudioRecord_JNI

#include <jni.h>

#include "sdk/android/native_api/jni_zero/jni_export.h"
#include "sdk/android/src/jni/jni_generator_helper.h"
// Macro for transition to enable_definition_macros=true.
#define DEFINE_JNI_FOR_WebRtcAudioRecord()

// Class Accessors
#ifndef org_webrtc_audio_WebRtcAudioRecord_clazz_defined
#define org_webrtc_audio_WebRtcAudioRecord_clazz_defined
inline jclass org_webrtc_audio_WebRtcAudioRecord_clazz(JNIEnv* env) {
  static const char kClassName[] = "org/webrtc/audio/WebRtcAudioRecord";
  static std::atomic<jclass> cached_class;
  return jni_zero::internal::LazyGetClass(env, kClassName, &cached_class);
}
#endif


namespace webrtc::jni {

// Java to native functions
JNI_ZERO_BOUNDARY_EXPORT void Java_org_webrtc_audio_WebRtcAudioRecord_nativeCacheDirectBufferAddress(
    JNIEnv* env,
    jobject jcaller,
    jlong nativeAudioRecordJni,
    jobject byteBuffer) {
  reinterpret_cast<AudioRecordJni*>(nativeAudioRecordJni)->CacheDirectBufferAddress(
      env,
      jni_zero::JavaParamRef<jobject>(env, jcaller),
      jni_zero::JavaParamRef<jobject>(env, byteBuffer));
}

JNI_ZERO_BOUNDARY_EXPORT void Java_org_webrtc_audio_WebRtcAudioRecord_nativeDataIsRecorded(
    JNIEnv* env,
    jobject jcaller,
    jlong nativeAudioRecordJni,
    jint bytes,
    jlong captureTimestampNs) {
  reinterpret_cast<AudioRecordJni*>(nativeAudioRecordJni)->DataIsRecorded(
      env,
      jni_zero::JavaParamRef<jobject>(env, jcaller),
      bytes,
      captureTimestampNs);
}


// Native to Java functions
static jni_zero::ScopedJavaLocalRef<jobject> Java_WebRtcAudioRecord_Constructor(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& context,
    const jni_zero::JavaRef<jobject>& audioManager) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioRecord", "<init>");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioRecord_clazz(env);
  CHECK_CLAZZ(env, clazz, clazz, nullptr);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "<init>",
      "(Landroid/content/Context;Landroid/media/AudioManager;)V",
      &cached_method_id);
  auto _ret = env->NewObject(clazz, call_context.method_id(), context.obj(), audioManager.obj());
  return jni_zero::ScopedJavaLocalRef<jobject>(env, _ret);
}

static jboolean Java_WebRtcAudioRecord_enableBuiltInAEC(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj,
    jboolean enable) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioRecord", "enableBuiltInAEC");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioRecord_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "enableBuiltInAEC",
      "(Z)Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id(), enable);
  return _ret;
}

static jboolean Java_WebRtcAudioRecord_enableBuiltInNS(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj,
    jboolean enable) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioRecord", "enableBuiltInNS");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioRecord_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "enableBuiltInNS",
      "(Z)Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id(), enable);
  return _ret;
}

static jint Java_WebRtcAudioRecord_initRecording(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj,
    JniIntWrapper sampleRate,
    JniIntWrapper channels) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioRecord", "initRecording");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioRecord_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, 0);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "initRecording",
      "(II)I",
      &cached_method_id);
  auto _ret = env->CallIntMethod(
      obj.obj(),
      call_context.method_id(),
      as_jint(sampleRate),
      as_jint(channels));
  return _ret;
}

static jboolean Java_WebRtcAudioRecord_isAcousticEchoCancelerSupported(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioRecord", "isAcousticEchoCancelerSupported");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioRecord_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "isAcousticEchoCancelerSupported",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static jboolean Java_WebRtcAudioRecord_isAudioConfigVerified(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioRecord", "isAudioConfigVerified");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioRecord_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "isAudioConfigVerified",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static jboolean Java_WebRtcAudioRecord_isAudioSourceMatchingRecordingSession(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioRecord", "isAudioSourceMatchingRecordingSession");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioRecord_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "isAudioSourceMatchingRecordingSession",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static jboolean Java_WebRtcAudioRecord_isNoiseSuppressorSupported(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioRecord", "isNoiseSuppressorSupported");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioRecord_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "isNoiseSuppressorSupported",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static void Java_WebRtcAudioRecord_setNativeAudioRecord(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj,
    jlong nativeAudioRecord) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioRecord", "setNativeAudioRecord");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioRecord_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "setNativeAudioRecord",
      "(J)V",
      &cached_method_id);
  env->CallVoidMethod(obj.obj(), call_context.method_id(), nativeAudioRecord);
}

static jboolean Java_WebRtcAudioRecord_startRecording(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioRecord", "startRecording");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioRecord_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "startRecording",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}

static jboolean Java_WebRtcAudioRecord_stopRecording(
    JNIEnv* env,
    const jni_zero::JavaRef<jobject>& obj) {
  jni_zero::CallNativeToJavaCallback("org/webrtc/audio/WebRtcAudioRecord", "stopRecording");
  static std::atomic<jmethodID> cached_method_id(nullptr);
  jclass clazz = org_webrtc_audio_WebRtcAudioRecord_clazz(env);
  CHECK_CLAZZ(env, obj.obj(), clazz, false);
  jni_zero::internal::JniJavaCallContext<true> call_context;
  call_context.Init<jni_zero::MethodID::TYPE_INSTANCE>(
      env,
      clazz,
      "stopRecording",
      "()Z",
      &cached_method_id);
  auto _ret = env->CallBooleanMethod(obj.obj(), call_context.method_id());
  return _ret;
}



}  // namespace webrtc::jni

#endif  // org_webrtc_audio_WebRtcAudioRecord_JNI
